[package]
name = "rust_ray"
version = "0.1.34"
edition = "2021"

[dependencies]
gl = "0.14.0"
glu-sys = "0.1.4"
rusttype = "0.9.3"
sdl2 = { version = "0.37.0", features = ["bundled", "static-link"]}

[build-dependencies]
vcpkg = "0.2.15"
